### ISSUE TITLE
Add Analysis.Effort.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-hub#347]
Add Analysis.Effort with is the sum of Issue.Effort.
Add to IssueReport.  Perhaps as part of the `application` information. 
```
application:
  id: 
  name:
  effort:
```
