### ISSUE TITLE
:sparkles: Support multi-container tasks.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-hub#598]
Motivation: Support analyzer (addon) with multiple provider images.

Add support multi-container tasks.  Each addon will support both _init_ containers and [SideCar](https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/) containers.  The addon spec will likely need to support this much in the same as as Pod spec.

```
container:
  image:
  name:
  imagePullPolicy:
  resources:
initContainer:
  - name:
    image:
    resources:
    imagePullPolicy:
    restartPolicy:
```

Should the container and initContainer be of type [v1.Core.Container](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#container-v1-core)?
