### ISSUE TITLE
[BUG] binary analysis on maven is failing

### ISSUE THREAD

**Issue by midays** [konveyor/tackle2-hub#613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Konveyor version

Feb 29, 2024

### Priority

Critical

### Current Behavior

the analysis fails

### Expected Behavior

The analysis should be completed successfully

### How Reproducible

Always (Default)

### Steps To Reproduce

1. Create a new applicatin for maven analysis
2. analyze the application

### Environment

```markdown
- OS:
```

### Anything else?

Analysis yaml output
```
id: 3
createTime: 2024-02-26T15:53:45.76859431Z
name: binary_test_app_test-app-modi147.2.windup
addon: analyzer
data:
    mode:
        artifact: ""
        binary: true
        withDeps: false
    rules:
        labels:
            excluded: []
            included:
                - konveyor.io/target=cloud-readiness
        path: ""
        tags:
            excluded: []
    scope:
        packages:
            excluded: []
            included: []
        withKnownLibs: false
    sources: []
    tagger:
        enabled: true
    targets: []
    verbosity: 0
application:
    id: 2
    name: binary_test_app_test-app-modi147
state: Failed
image: quay.io/konveyor/tackle2-addon-analyzer:latest
pod: konveyor-tackle/task-3-nc5p7
started: 2024-02-26T15:53:46.240171522Z
terminated: 2024-02-26T15:54:04.6889708Z
bucket:
    id: 5
    name: ""
errors:
    - severity: Error
      description: exit status 1
    - severity: Error
      description: 'Pod failed: Error'
activity:
    - Fetching application.
    - '[CMD] Running: /usr/bin/ssh-agent -a /tmp/agent.1'
    - '[CMD] /usr/bin/ssh-agent succeeded.'
    - '[SSH] Agent started.'
    - '[MVN] Using credentials (id=3) moQOFB.'
    - '[FILE] Created /addon/settings.xml.'
    - '[MVN] Using settings file(path=/addon/settings.xml).'
    - '[MVN] Fetch artifact io.konveyor.demo:customers-tomcat:0.0.1-SNAPSHOT:war.'
    - '[CMD] Running: /usr/bin/mvn dependency:copy -Dartifact=io.konveyor.demo:customers-tomcat:0.0.1-SNAPSHOT:war -Dmdep.useBaseVersion=true -DoutputDirectory=/addon/bin/maven -Dmaven.repo.local=/cache/m2 -Dmaven.wagon.http.ssl.insecure=true -s /addon/settings.xml'
    - '[CMD] /usr/bin/mvn failed: exit status 1'
attached:
    - id: 348
      name: ssh-agent.output
      activity: 2
    - id: 349
      name: mvn.output
      activity: 9

```
