### ISSUE TITLE
:sparkles: Add application manifest.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-hub#808]
Application (deployment) manifests define how applications are deployed on a platform.

Add manifest model, REST resource and API endpoint:
- /manifests
  - filter: application.name 
- /applications/:id/manifest   (latest)

query param:
 - decrypted - decrypt secret
 - injected - inject (replace) _secret_ references

Manifest (model):
- content _any_
- secret _any_

The secret is encrypted.
The content is a document with values that may be a reference to a secret.  The format is $(ref).
The API endpoint will support decryption and injecting (replacing) the _secret_ references in the content.

Example (manifest):
```yaml
id: 1
content:
  name:  Test
  namespace: Test
  database:
    URL: Test
    user: $(user)
    password: $(password)
secret:
  user: Elmer
  password: ZX9AZK
```
