### ISSUE TITLE
:sparkles: Add json-schema support.

### ISSUE THREAD

**Issue by jortel** [konveyor/tackle2-hub#810]
Introduces a new concept of named schemas defining versioned schemas.  Schemas are defined using the [ json-schema](https://json-schema.org/) syntax/standard.

Not sure if this is a seeded model or a CR.

The Schema is:
- name:
- domain:
- variant:
- subject:
- []versions:
  - definition
  - migration

The domain, variant and subject provide a hierarchical reference used a locator.  API users (the UI) can query for a schema based on these fields.  Endpoint: `/schema/:domain/:variant/:subject`.  As an example, for schema driven fields in the inventory, here is an example for platform specific fields:  `/schema/platform/cf/coordinates`.  The variant `cf` is the Platform.Kind.

The hub will perform:
- schema/data migration.  The _patch_ field contains a yq ([yaml-query](https://mikefarah.gitbook.io/yq)) expression used to migrate (patch) the document structure and content. This will tie into the existing _migration_ mechanism for the data model.
- document schema validation.

Object in the inventory may have fields containing _schema-driven_ json documents.  For example the Application may have a platform (type) specific field.  For example, the application's coordinates in the source platform:
Application:
  - coordinates Document

Where Document is defined as:

Document:
- schema:   // _schema name_
- content:  // _document content_

Routes:
- /schema - routes
- /schemas - schema collection
- /schemas/:name - get by name.
- /schemas/jsd/:domain/:variant/:subject - get latest version key.

---

Examples using `Person` because it's relatable.

Person (v1):
```yaml
name: Elmer Fudd
age: 44
phone: 222-333-4444
```

Person (v2):
```yaml
name: Elmer Fudd
age: 44
phone:
  npa: 222
  nxx: 333
  number: 4444
```

Schema (json-schema):
```yaml
---
kind: Schema
apiVersion: tackle.konveyor.io/v1alpha1
metadata:
  name: people
  namespace: konveyor-tackle
spec:
  domain: people
  variant: manager
  subject: basic
  versions:
  - definition:
        '$schema': https://json-schema.org/draft/2020-12/schema
        title: Person
        type: object
        required:
          - name
          - age
          - phone
        properties:
          name:
            type: string
          age:
            type: integer
            minimum: 0
          phone:
            type: string
            pattern: '^\d{3}-\d{3}-\d{4}$'
            description: Phone number in the format 555-444-8888
  - definition:
        '$schema': https://json-schema.org/draft/2020-12/schema
        title: Person
        type: object
        required:
          - name
          - age
          - phone
        properties:
          name:
            type: string
          age:
            type: integer
            minimum: 0
          phone:
            type: object
            required:
              - npa
              - nxx
              - number
            properties:
              npa:
                type: string
                pattern: '^\d{3}$'
                description: 3-digit area code
              nxx:
                type: string
                pattern: '^\d{3}$'
                description: 3-digit exchange code
              number:
                type: string
                pattern: '^\d{4}$'
                description: 4-digit line number
    migration: >
      .phone |= (split("-") 
        | {
            "npa": .[0],
            "nxx": .[1],
            "number": .[2]
          })
```
