### ISSUE TITLE
[BUG] Zero effort points

### ISSUE THREAD

**Issue by mguetta1** [konveyor/tackle2-hub#843]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Konveyor version

upstream/main

### Priority

Blocker

### Current Behavior

MTA UI shows no analysis effort points.

![Image](https://github.com/user-attachments/assets/0d61c8a1-79ea-4ed6-9e08-43214b478da3)

The analysis report yaml file looks OK
```
---
id: 1
createUser: admin.noauth
createTime: 2025-06-16T10:30:51.478123877Z
application:
  id: 1
  name: ""
effort: 270
commit: a17f2b02b3402a6f8eb2f21cf57c75c8a7783cd5

issues: 
...
```

### How Reproducible

Always (Default)

### Environment

```markdown

```
